# Prometheus configuration file
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'posgresql-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

# Alerting rules
rule_files:
  - "rules.yml"

# Alert manager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
