# Alerting rules

groups:
  - name: grafana
    rules:
      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          title: "Grafana is down"
          description: "Grafana is down for more than 2 minute"
  # PostgreSQL (requires PostgreSQL exporter)
  - name: postgres
    rules:
      # Alert for PostgreSQL down
      - alert: PostgresDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          title: "PostgreSQL is down"
          description: "PostgreSQL has been down for more than 1 minutes"
      # Alert for abnormal number of connections
      - alert: PostgresAbnormalConnections
        expr: pg_stat_activity_count > 4
        for: 1m
        labels:
          severity: warning
        annotations:
          title: "PostgreSQL Abnormal Connections"
          description: "PostgreSQL has more than 4 connections"