# Generated by Django 5.0.7 on 2024-08-19 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=160)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
