{
 "title": "42 Transcendence Dashboard",
 "tags": [ "transcendence" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Most Used Tables",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT schemaname, relname, n_live_tup FROM pg_stat_user_tables ORDER BY n_live_tup DESC LIMIT 5;"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM pg_stat_activity WHERE state = 'active';"
    }
   ]
  },
  {
   "title": "Number of Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT pg_size_pretty(pg_database_size('test_db'));"
    }
   ]
  },
  {
   "title": "Host System Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by(instance) / sum(rate(node_cpu_seconds_total{}[5m])) by(instance) * 100\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) * 100 / node_memory_MemTotal_bytes\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1000000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemFree_bytes / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Longuest Running Query",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    query,\n    state,\n    now() - xact_start AS duration\nFROM \n    pg_stat_activity\nWHERE \n    state != 'idle'\n    AND state != 'idle in transaction (aborted)'\nORDER BY \n    duration DESC\nLIMIT 5;\n"
    }
   ]
  }
 ]
}