{
 "title": "Postgres Dashboard",
 "time": { "from": "2024-09-03T06:22:02.298Z", "to": "2024-09-03T18:22:02.298Z" },
 "panels": [
  {
   "title": "Most Used Tables",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT schemaname, relname, n_live_tup FROM pg_stat_user_tables ORDER BY n_live_tup DESC LIMIT 5;"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM pg_stat_activity WHERE state = 'active';"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT pg_size_pretty(pg_database_size('test_db'));"
    }
   ]
  },
  {
   "title": "Number of Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';"
    }
   ]
  },
  {
   "title": "Longuest Running Query",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    query,\n    state,\n    now() - xact_start AS duration\nFROM \n    pg_stat_activity\nWHERE \n    state != 'idle'\n    AND state != 'idle in transaction (aborted)'\nORDER BY \n    duration DESC\nLIMIT 5;\n"
    }
   ]
  }
 ]
}