# Generated by Django 5.1 on 2024-08-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_test_user_delete_testuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_user',
            name='observator',
            field=models.BooleanField(default=False),
        ),
    ]
