# Generated by Django 5.1 on 2024-08-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_test_user_observator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_user',
            old_name='observator',
            new_name='spectator',
        ),
    ]
