# Configuration file version
apiVersion: 1

# List of datasources to insert or update
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  
  - name: PostgreSQL
    type: postgres
    url: postgres://$POSTGRES_USER:$(cat $POSTGRES_PASSWORD_FILE)@postgres:5432/$POSTGRES_DB
    access: proxy
    isDefault: false
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    secureJsonData:
      password: $(cat $POSTGRES_PASSWORD_FILE)
    jsonData:
      sslmode: disable
    readOnly: false