# Variables expansion
# $__file{VAR__FILE} will be replaced by the content of the file pointed by VAR__FILE
# $__env{VAR__ENV} will be replaced by the value of the environment variable VAR__ENV
# ${VAR} will be replaced by the value of the environment variable VAR

# Configuration file version
apiVersion: 1

# List of datasources to insert or update
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

  - name: PostgreSQL
    type: postgres
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    user: ${POSTGRES_READONLY_USER}
    access: proxy
    isDefault: false
    database: ${POSTGRES_DB}
    secureJsonData:
      password: $__file{/run/secrets/db_readonly_password}
    jsonData:
      sslmode: disable
    readOnly: true